### ISSUE TITLE
Scheduler misinterprets threshold

### ISSUE THREAD

**Issue by Knoop** [2IMN00-16/Scheduler#5]
The priority threshold should be inclusive, but is exclusive. So if a task specifies a threshold priority of 2, then every task with priority 2 or larger should be able to interrupt it.

**Comment by Prathyusha12** [comment]
I believe the priority of the preempting task must be strictly greater than that of the pre-empted task. This is not a bug. It is by design.

**Comment by Prathyusha12** [comment]
The same goes with thresholds. The threshold should not be inclusive. The priority of the preempting task must be strictly greater than the threshold of the preempted task. The protocol defines it in such a way and it has been adhered to in the scheduler.

**Comment by Knoop** [comment]
Fair point, I stand corrected.
