### ISSUE TITLE
Tasks with same properties except for their name are mixed

### ISSUE THREAD

**Issue by Knoop** [2IMN00-16/Scheduler#6]
This continues on #3. Two tasks with the same properties except for their name are confused in the definition of tasks in the output grasp script. This input relies on #5 not being fixed yet. If #5 is fixed, replace the property `"Threshold"` by 1 for both tasks. 

input.json:
```json
{
	"Tasks": [ 
		{
			"Name": "Task 1",
			"Priority": 0,
			"Computation": 10,
			"Period": 50,
			"Deadline": 50,
			"Threshold": 0
		},
		{
			"Name": "Task 2",
			"Priority": 0,
			"Computation": 10,
			"Period": 50,
			"Deadline": 50,
			"Threshold": 0
		}
	],
	"Duration" : 30
}
```

schedule.grasp:
```
newTask task0 -priority 0 -name "Task 1" 
newTask task0 -priority 0 -name "Task 1" 
plot 0 jobArrived job0.0 task0 
plot 0 jobArrived job1.0 task1 
plot 0 jobResumed job0.0 
plot 10 jobCompleted job0.0 
plot 10 jobResumed job1.0 
plot 20 jobCompleted job1.0 
plot 50 jobDeadline job0.0 
plot 50 jobDeadline job1.0 
```

**Comment by Knoop** [comment]
Arguably two tasks should not be able to have the same priority. However, this scheduler does not specify that that is forbidden and as such the app allows for multiple tasks to have the same priority

**Comment by Prathyusha12** [comment]
The paper says clearly that the priorities have to be unique so we will disallow two tasks with same priorities.

**Comment by Knoop** [comment]
Fair enough. The app has been updated to make sure task sets do not contain multiple tasks with the same priority
